language: node_js
node_js:
  - lts/dubnium
  - node
sudo: false
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: p6+1b1/lFM70svYv5V5337bKNMn6IVndw25hsA0NJwI5tUcLi2TMSFA9VRf8GdozGwhhGM3Fut5QwKCt3Pgj/nQcx6AzWx8ZciIhJYaYHOmys7tApESf/ZAbQUdxvE15ptJOx8OBQovzQ+kxE76BaBganLy4cIM6H5xUMbvGd/Q=
  file:
    - 'double-metaphone.js'
    - 'double-metaphone.min.js'
  on:
    tags: true
